# 2023/03/13
reference: Causal Consistency Network_A Collaborative Multi-machine Generalization Method for Bearing Fault Diagnosis, Lijie
dataset_type: fan # bearing or fan
fan_section: sec00 # sec00, sec01, sec02
dataset_debug: False
use_cuda: True
device: cpu
# Bearing dataset setting
use_angular_resample: True
use_fft: False # input data form (raw original signal or frequency spectrum)
use_hilbert_envelope: True
use_domain_weight: True
data_length: 2560
unified_Os: 350 # the number of sampling points per rad


# basic model parameters
batch_size: 64 # 32 for fan, 64 for bearing
num_classes: 3 # 2 for fan, 3 for bearing


# basic training parameters
steps: 200 # the number of iteration, 200 for bearing and 100 for fan (because the fan dataset is small)
checkpoint_freq: 1
# weight_decay: 0.0001
lr: 0.0001

lbda_cc: 1
lbda_ct: 1










