# 2023/03/28
reference: A hybrid generalization network for intelligent fault diagnosis of rotating machinery under unseen working conditions
dataset_debug: False
dataset_type: fan # bearing or fan
fan_section: sec00 # sec00, sec01, sec02
use_cuda: True
device: cpu
use_fft: False # input data form (raw original signal or frequency spectrum)
use_domain_weight: False
use_hilbert_envelope: True
data_length: 2560
unified_Os: 350 # 转轴每转一圈采样点的数目
use_angular_resample: True


# basic model parameters
batch_size: 64 # 32 for fan, 64 for bearing
num_classes: 3 # 2 for fan, 3 for bearing


# basic training parameters
steps: 200 # the number of iteration, 200 for bearing and 100 for fan (because the fan dataset is small)
checkpoint_freq: 1
# weight_decay: 0.0001
lr: 0.0001

triplet_loss_margin: 2
lbda_t: 0.01 # 0.01
lbda_d: 0.01










